language: python

python: 3.6

install: 
  - pip install -r requirements.txt
  - pip install .
  - mkdir credentials
  - echo "$YOUTUBE_DEVELOPER_KEY" > "credentials/developer_key"
  - echo "$CHANNEL_CREDENTIALS" > "credentials/credentials.storage"
  - echo "$CLIENT_SECRET" > "credentials/client_secret.json"
  - cat credentials/client_secret.json
  - cat credentials/credentials.storage 

script: 
  - python setup.py test --pytest-args "tests/ --doctest-modules -v --cov simple_youtube_api --cov-report term-missing"

after_success: 
  - coveralls
