language: python

python: 3.6

install: 
  - pip install .

script: 
  - python setup.py test --pytest-args "tests/ --doctest-modules -v --cov simple_youtube_api --cov-report term-missing"

after_success: 
  - coveralls